# Autogenerated by nbdev

d = { 'settings': {'branch': 'main', 'doc_baseurl': '/', 'doc_host': '', 'git_url': '', 'lib_path': 'hyperrun'},
  'syms': { 'hyperrun.core': {'hyperrun.core.search_code': ('core.html#search_code', 'hyperrun/core.py')},
            'hyperrun.ui': { 'hyperrun.ui.ai_bubble_stream': ('ui.html#ai_bubble_stream', 'hyperrun/ui.py'),
                             'hyperrun.ui.ask': ('ui.html#ask', 'hyperrun/ui.py'),
                             'hyperrun.ui.chat_panel': ('ui.html#chat_panel', 'hyperrun/ui.py'),
                             'hyperrun.ui.close_chat': ('ui.html#close_chat', 'hyperrun/ui.py'),
                             'hyperrun.ui.get': ('ui.html#get', 'hyperrun/ui.py'),
                             'hyperrun.ui.home': ('ui.html#home', 'hyperrun/ui.py'),
                             'hyperrun.ui.model_options': ('ui.html#model_options', 'hyperrun/ui.py'),
                             'hyperrun.ui.save_settings': ('ui.html#save_settings', 'hyperrun/ui.py'),
                             'hyperrun.ui.settings_panel': ('ui.html#settings_panel', 'hyperrun/ui.py'),
                             'hyperrun.ui.stream_response': ('ui.html#stream_response', 'hyperrun/ui.py'),
                             'hyperrun.ui.user_bubble': ('ui.html#user_bubble', 'hyperrun/ui.py')}}}
