# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['sp', 'chat', 'search_code', 'ensure_index']

# %% ../nbs/00_core.ipynb #9beed022
import json
import asyncio
import os


async def search_code(query: str, k: int = 5) -> list[dict]:
    """Search the codebase semantically using ColGrep."""
    proc = await asyncio.create_subprocess_exec(
        "colgrep",
        "-e",
        "^def |^class ",
        query,
        "-k",
        str(k),
        "--json",
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        cwd=os.environ.get("HYPERRUN_REPO_PATH"),
    )
    stdout, _ = await proc.communicate()
    return json.loads(stdout)

# %% ../nbs/00_core.ipynb #aea40c68
from pathlib import Path


async def ensure_index():
    repo = os.environ.get("HYPERRUN_REPO_PATH", ".")
    idx = Path(repo) / ".colgrep"
    if not idx.exists():
        proc = await asyncio.create_subprocess_exec("colgrep", "init", cwd=repo)
        await proc.wait()


# %% ../nbs/00_core.ipynb #2fb3c9e3
from lisette import AsyncChat
from dotenv import load_dotenv

load_dotenv()
sp = """You have a `search_code` tool that searches a Python codebase using ColGrep (semantic code search).
It uses hybrid search: regex pre-filters to functions/classes, then ranks semantically.
- Increase `k` if you need more results.
- Scores are more accurate when functions have rich docstrings.
- You can call the tool multiple times with different queries to find related code."""

chat = AsyncChat("claude-sonnet-4-20250514", sp=sp, tools=[search_code])
